/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tracktopell.dao.builder.xpressosystems.framework.view;

import java.awt.HeadlessException;
import java.awt.event.MouseEvent;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author alfredo
 */
public class WizzardPanel extends javax.swing.JPanel {

	/**
	 * Creates new form WizzardPanel
	 */
	public WizzardPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        importAndChoicePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xmlVPFilePath = new javax.swing.JTextField();
        parseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vpTablesToChoice = new javax.swing.JTable();
        tablesAndColumnsCustPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablesPropertiesTbl = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        columnsPropertiesTbl = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablesMetaPropertiesTbl = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        columnsMetaPropertiesTbl = new javax.swing.JTable();
        generatedOutputPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        generateJavaSrc = new javax.swing.JCheckBox();
        javaSrcFile = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        generateSQLSchemma = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        sqlSchemma = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        generateXSMapping = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        xsMapping = new javax.swing.JTextField();
        resultsPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        resultsArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        cardPanel.setLayout(new java.awt.CardLayout());

        importAndChoicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Import & Choice Tables"));
        importAndChoicePanel.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Visual Paradigm XML Project:");
        jPanel4.add(jLabel1);

        xmlVPFilePath.setColumns(20);
        xmlVPFilePath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xmlVPFilePathMouseClicked(evt);
            }
        });
        jPanel4.add(xmlVPFilePath);

        parseBtn.setText("Parse & Import");
        jPanel4.add(parseBtn);

        importAndChoicePanel.add(jPanel4, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(vpTablesToChoice);

        importAndChoicePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        cardPanel.add(importAndChoicePanel, "importAndChoicePanel");

        tablesAndColumnsCustPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tables & Columns customizer"));
        tablesAndColumnsCustPanel.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel7.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tables");
        jPanel7.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Columns");
        jPanel7.add(jLabel3);

        tablesAndColumnsCustPanel.add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        tablesPropertiesTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tablesPropertiesTbl);

        jPanel5.add(jScrollPane2);

        columnsPropertiesTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(columnsPropertiesTbl);

        jPanel5.add(jScrollPane3);

        tablesMetaPropertiesTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tablesMetaPropertiesTbl);

        jPanel5.add(jScrollPane4);

        columnsMetaPropertiesTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(columnsMetaPropertiesTbl);

        jPanel5.add(jScrollPane5);

        tablesAndColumnsCustPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        cardPanel.add(tablesAndColumnsCustPanel, "tablesAndColumnsCustPanel");

        generatedOutputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Generated Output"));
        generatedOutputPanel.setLayout(new java.awt.GridLayout(4, 1));

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        generateJavaSrc.setText("Java Sources Dir:");
        jPanel9.add(generateJavaSrc);

        javaSrcFile.setColumns(20);
        javaSrcFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                javaSrcFileMouseClicked(evt);
            }
        });
        jPanel9.add(javaSrcFile);

        generatedOutputPanel.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        generateSQLSchemma.setText("SQL Schemma File:");
        jPanel10.add(generateSQLSchemma);
        jPanel10.add(jLabel5);

        sqlSchemma.setColumns(20);
        jPanel10.add(sqlSchemma);

        generatedOutputPanel.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        generateXSMapping.setText("SQL XpressoSystems Mapping File:");
        jPanel11.add(generateXSMapping);
        jPanel11.add(jLabel6);

        xsMapping.setColumns(20);
        xsMapping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xsMappingMouseClicked(evt);
            }
        });
        jPanel11.add(xsMapping);

        generatedOutputPanel.add(jPanel11);

        cardPanel.add(generatedOutputPanel, "generatedOutputPanel");

        resultsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));
        resultsPanel.setLayout(new java.awt.BorderLayout());

        resultsArea.setBackground(java.awt.Color.black);
        resultsArea.setColumns(20);
        resultsArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        resultsArea.setForeground(java.awt.Color.green);
        resultsArea.setRows(5);
        jScrollPane6.setViewportView(resultsArea);

        resultsPanel.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        cardPanel.add(resultsPanel, "resultsPanel");

        add(cardPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        backBtn.setText("Atras");
        jPanel3.add(backBtn);

        nextBtn.setText("Siguiente");
        jPanel3.add(nextBtn);

        finishBtn.setText("Finalizar");
        jPanel3.add(finishBtn);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void xmlVPFilePathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xmlVPFilePathMouseClicked
		searchFile(evt,xmlVPFilePath);
    }//GEN-LAST:event_xmlVPFilePathMouseClicked

    private void javaSrcFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_javaSrcFileMouseClicked
        searchFile(evt,javaSrcFile);
    }//GEN-LAST:event_javaSrcFileMouseClicked

    private void xsMappingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xsMappingMouseClicked
        searchFile(evt,xsMapping);
    }//GEN-LAST:event_xsMappingMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JTable columnsMetaPropertiesTbl;
    private javax.swing.JTable columnsPropertiesTbl;
    private javax.swing.JButton finishBtn;
    private javax.swing.JCheckBox generateJavaSrc;
    private javax.swing.JCheckBox generateSQLSchemma;
    private javax.swing.JCheckBox generateXSMapping;
    private javax.swing.JPanel generatedOutputPanel;
    private javax.swing.JPanel importAndChoicePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField javaSrcFile;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton parseBtn;
    private javax.swing.JTextArea resultsArea;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JTextField sqlSchemma;
    private javax.swing.JPanel tablesAndColumnsCustPanel;
    private javax.swing.JTable tablesMetaPropertiesTbl;
    private javax.swing.JTable tablesPropertiesTbl;
    private javax.swing.JTable vpTablesToChoice;
    private javax.swing.JTextField xmlVPFilePath;
    private javax.swing.JTextField xsMapping;
    // End of variables declaration//GEN-END:variables

	private void searchFile(MouseEvent evt,JTextField tf) throws HeadlessException {
		if (evt.getClickCount() == 2) {
			JFileChooser fileChooser = new JFileChooser();
			int showOpenDialog = fileChooser.showOpenDialog(this);

			if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
				tf.setText(fileChooser.getSelectedFile().getAbsolutePath());
			}
		}
	}

	/**
	 * @return the backBtn
	 */
	public javax.swing.JButton getBackBtn() {
		return backBtn;
	}

	/**
	 * @return the columnsMetaPropertiesTbl
	 */
	public javax.swing.JTable getColumnsMetaPropertiesTbl() {
		return columnsMetaPropertiesTbl;
	}

	/**
	 * @return the columnsPropertiesTbl
	 */
	public javax.swing.JTable getColumnsPropertiesTbl() {
		return columnsPropertiesTbl;
	}

	/**
	 * @return the finishBtn
	 */
	public javax.swing.JButton getFinishBtn() {
		return finishBtn;
	}

	/**
	 * @return the generateJavaSrc
	 */
	public javax.swing.JCheckBox getGenerateJavaSrc() {
		return generateJavaSrc;
	}

	/**
	 * @return the generateSQLSchemma
	 */
	public javax.swing.JCheckBox getGenerateSQLSchemma() {
		return generateSQLSchemma;
	}

	/**
	 * @return the generateXSMapping
	 */
	public javax.swing.JCheckBox getGenerateXSMapping() {
		return generateXSMapping;
	}

	/**
	 * @return the generatedOutputPanel
	 */
	public javax.swing.JPanel getGeneratedOutputPanel() {
		return generatedOutputPanel;
	}

	/**
	 * @return the importAndChoicePanel
	 */
	public javax.swing.JPanel getImportAndChoicePanel() {
		return importAndChoicePanel;
	}

	/**
	 * @return the javaSrcFile
	 */
	public javax.swing.JTextField getJavaSrcFile() {
		return javaSrcFile;
	}

	/**
	 * @return the nextBtn
	 */
	public javax.swing.JButton getNextBtn() {
		return nextBtn;
	}

	/**
	 * @return the parseBtn
	 */
	public javax.swing.JButton getParseBtn() {
		return parseBtn;
	}

	/**
	 * @return the resultsArea
	 */
	public javax.swing.JTextArea getResultsArea() {
		return resultsArea;
	}

	/**
	 * @return the resultsPanel
	 */
	public javax.swing.JPanel getResultsPanel() {
		return resultsPanel;
	}

	/**
	 * @return the sqlSchemma
	 */
	public javax.swing.JTextField getSqlSchemma() {
		return sqlSchemma;
	}

	/**
	 * @return the tablesAndColumnsCustPanel
	 */
	public javax.swing.JPanel getTablesAndColumnsCustPanel() {
		return tablesAndColumnsCustPanel;
	}

	/**
	 * @return the tablesMetaPropertiesTbl
	 */
	public javax.swing.JTable getTablesMetaPropertiesTbl() {
		return tablesMetaPropertiesTbl;
	}

	/**
	 * @return the tablesPropertiesTbl
	 */
	public javax.swing.JTable getTablesPropertiesTbl() {
		return tablesPropertiesTbl;
	}

	/**
	 * @return the vpTablesToChoice
	 */
	public javax.swing.JTable getVpTablesToChoice() {
		return vpTablesToChoice;
	}

	/**
	 * @return the xmlVPFilePath
	 */
	public javax.swing.JTextField getXmlVPFilePath() {
		return xmlVPFilePath;
	}

	/**
	 * @return the xsMapping
	 */
	public javax.swing.JTextField getXsMapping() {
		return xsMapping;
	}

	/**
	 * @return the cardPanel
	 */
	public javax.swing.JPanel getCardPanel() {
		return cardPanel;
	}
}
